name = "LatexPrint"
uuid = "d2208f48-c256-5759-9089-c25ed2a93924"
author = ["Edward Scheinerman <ers@jhu.edu>"]
version = "0.1.1"


[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
